// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package queries

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, account_id, refresh_token, key_id, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSessionParams struct {
	ID           string
	AccountID    int64
	RefreshToken []byte
	KeyID        string
	UserAgent    string
	ExpiresAt    time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.AccountID,
		arg.RefreshToken,
		arg.KeyID,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	return err
}

const deleteAccountSessions = `-- name: DeleteAccountSessions :exec
DELETE FROM sessions WHERE account_id = $1
`

func (q *Queries) DeleteAccountSessions(ctx context.Context, accountID int64) error {
	_, err := q.db.Exec(ctx, deleteAccountSessions, accountID)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT s.id, s.account_id, s.refresh_token, s.key_id, s.user_agent, s.created_at, s.last_seen_at, s.roles_checked_at, s.expires_at, a.id, a.issuer, a.sub, a.name, a.email, a.roles, a.admin, a.created_at, a.last_login_at, a.roles_checked_at
FROM sessions s
JOIN accounts a ON a.id = s.account_id
WHERE s.id = $1 AND s.expires_at > now()
`

type GetSessionRow struct {
	Session Session
	Account Account
}

func (q *Queries) GetSession(ctx context.Context, id string) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.AccountID,
		&i.Session.RefreshToken,
		&i.Session.KeyID,
		&i.Session.UserAgent,
		&i.Session.CreatedAt,
		&i.Session.LastSeenAt,
		&i.Session.RolesCheckedAt,
		&i.Session.ExpiresAt,
		&i.Account.ID,
		&i.Account.Issuer,
		&i.Account.Sub,
		&i.Account.Name,
		&i.Account.Email,
		&i.Account.Roles,
		&i.Account.Admin,
		&i.Account.CreatedAt,
		&i.Account.LastLoginAt,
		&i.Account.RolesCheckedAt,
	)
	return i, err
}

const listAccountSessions = `-- name: ListAccountSessions :many
SELECT id, account_id, refresh_token, key_id, user_agent, created_at, last_seen_at, roles_checked_at, expires_at FROM sessions WHERE account_id = $1 AND expires_at > now() ORDER BY last_seen_at DESC
`

func (q *Queries) ListAccountSessions(ctx context.Context, accountID int64) ([]Session, error) {
	rows, err := q.db.Query(ctx, listAccountSessions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.RefreshToken,
			&i.KeyID,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.RolesCheckedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSession = `-- name: LockSession :one
SELECT id, account_id, refresh_token, key_id, user_agent, created_at, last_seen_at, roles_checked_at, expires_at FROM sessions WHERE id = $1 AND expires_at > now() FOR UPDATE
`

func (q *Queries) LockSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, lockSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RefreshToken,
		&i.KeyID,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RolesCheckedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const saveSessionRefresh = `-- name: SaveSessionRefresh :exec
UPDATE sessions
SET refresh_token = $1, key_id = $2, roles_checked_at = clock_timestamp(), last_seen_at = clock_timestamp()
WHERE id = $3
`

type SaveSessionRefreshParams struct {
	RefreshToken []byte
	KeyID        string
	ID           string
}

func (q *Queries) SaveSessionRefresh(ctx context.Context, arg SaveSessionRefreshParams) error {
	_, err := q.db.Exec(ctx, saveSessionRefresh, arg.RefreshToken, arg.KeyID, arg.ID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now() WHERE id = $1 AND last_seen_at < now() - interval '1 minute'
`

func (q *Queries) TouchSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}

const updateAccountRoles = `-- name: UpdateAccountRoles :exec
UPDATE accounts
SET name = $1, email = $2, roles = $3::text[], admin = $4, roles_checked_at = clock_timestamp()
WHERE id = $5
`

type UpdateAccountRolesParams struct {
	Name  string
	Email string
	Roles []string
	Admin bool
	ID    int64
}

func (q *Queries) UpdateAccountRoles(ctx context.Context, arg UpdateAccountRolesParams) error {
	_, err := q.db.Exec(ctx, updateAccountRoles,
		arg.Name,
		arg.Email,
		arg.Roles,
		arg.Admin,
		arg.ID,
	)
	return err
}

const upsertAccount = `-- name: UpsertAccount :one
INSERT INTO accounts (issuer, sub, name, email, roles, admin, last_login_at, roles_checked_at)
VALUES ($1, $2, $3, $4, $5::text[], $6, now(), now())
ON CONFLICT (issuer, sub) DO UPDATE
SET name = excluded.name, email = excluded.email, roles = excluded.roles, admin = excluded.admin,
    last_login_at = now(), roles_checked_at = now()
RETURNING id, issuer, sub, name, email, roles, admin, created_at, last_login_at, roles_checked_at
`

type UpsertAccountParams struct {
	Issuer string
	Sub    string
	Name   string
	Email  string
	Roles  []string
	Admin  bool
}

func (q *Queries) UpsertAccount(ctx context.Context, arg UpsertAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, upsertAccount,
		arg.Issuer,
		arg.Sub,
		arg.Name,
		arg.Email,
		arg.Roles,
		arg.Admin,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Issuer,
		&i.Sub,
		&i.Name,
		&i.Email,
		&i.Roles,
		&i.Admin,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.RolesCheckedAt,
	)
	return i, err
}
