// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hits.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const confirmBeacon = `-- name: ConfirmBeacon :execrows
UPDATE hits
SET beacon_confirmed = true,
    engaged_ms = GREATEST(COALESCE(engaged_ms, 0), $1::bigint),
    visitor_kind = 'human'
WHERE id = $2
  AND visitor_kind IN ('human', 'human-unconfirmed')
  AND ts > $3
`

type ConfirmBeaconParams struct {
	EngagedMs int64
	ID        uuid.UUID
	NotBefore time.Time
}

func (q *Queries) ConfirmBeacon(ctx context.Context, arg ConfirmBeaconParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmBeacon, arg.EngagedMs, arg.ID, arg.NotBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getHit = `-- name: GetHit :one
SELECT id, ts, path, page_id, locale, release_label, format, status, visitor_kind, bot_name, verified, arrival_channel, referrer_host, referrer_name, utm_source, utm_medium, utm_campaign, utm_term, utm_content, country, user_agent, visitor_id, daily_hash, internal, beacon_confirmed, engaged_ms FROM hits WHERE id = $1
`

func (q *Queries) GetHit(ctx context.Context, id uuid.UUID) (Hit, error) {
	row := q.db.QueryRow(ctx, getHit, id)
	var i Hit
	err := row.Scan(
		&i.ID,
		&i.Ts,
		&i.Path,
		&i.PageID,
		&i.Locale,
		&i.ReleaseLabel,
		&i.Format,
		&i.Status,
		&i.VisitorKind,
		&i.BotName,
		&i.Verified,
		&i.ArrivalChannel,
		&i.ReferrerHost,
		&i.ReferrerName,
		&i.UtmSource,
		&i.UtmMedium,
		&i.UtmCampaign,
		&i.UtmTerm,
		&i.UtmContent,
		&i.Country,
		&i.UserAgent,
		&i.VisitorID,
		&i.DailyHash,
		&i.Internal,
		&i.BeaconConfirmed,
		&i.EngagedMs,
	)
	return i, err
}

const insertHit = `-- name: InsertHit :exec
INSERT INTO hits (
    id, ts, path, page_id, locale, release_label, format, status, visitor_kind, bot_name, verified,
    arrival_channel, referrer_host, referrer_name, utm_source, utm_medium, utm_campaign, utm_term, utm_content,
    country, user_agent, visitor_id, daily_hash, internal
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16, $17, $18, $19,
    $20, $21, $22, $23, $24
)
`

type InsertHitParams struct {
	ID             uuid.UUID
	Ts             time.Time
	Path           string
	PageID         *string
	Locale         *string
	ReleaseLabel   string
	Format         string
	Status         int64
	VisitorKind    string
	BotName        *string
	Verified       *bool
	ArrivalChannel *string
	ReferrerHost   *string
	ReferrerName   *string
	UtmSource      *string
	UtmMedium      *string
	UtmCampaign    *string
	UtmTerm        *string
	UtmContent     *string
	Country        *string
	UserAgent      string
	VisitorID      *string
	DailyHash      string
	Internal       bool
}

func (q *Queries) InsertHit(ctx context.Context, arg InsertHitParams) error {
	_, err := q.db.Exec(ctx, insertHit,
		arg.ID,
		arg.Ts,
		arg.Path,
		arg.PageID,
		arg.Locale,
		arg.ReleaseLabel,
		arg.Format,
		arg.Status,
		arg.VisitorKind,
		arg.BotName,
		arg.Verified,
		arg.ArrivalChannel,
		arg.ReferrerHost,
		arg.ReferrerName,
		arg.UtmSource,
		arg.UtmMedium,
		arg.UtmCampaign,
		arg.UtmTerm,
		arg.UtmContent,
		arg.Country,
		arg.UserAgent,
		arg.VisitorID,
		arg.DailyHash,
		arg.Internal,
	)
	return err
}

const insertOutboundClick = `-- name: InsertOutboundClick :exec
INSERT INTO outbound_clicks (
    id, ts, from_path, page_id, locale, release_label, target, visitor_kind, bot_name, verified,
    visitor_id, daily_hash, internal, country
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14
)
`

type InsertOutboundClickParams struct {
	ID           uuid.UUID
	Ts           time.Time
	FromPath     string
	PageID       *string
	Locale       *string
	ReleaseLabel string
	Target       string
	VisitorKind  string
	BotName      *string
	Verified     *bool
	VisitorID    *string
	DailyHash    string
	Internal     bool
	Country      *string
}

func (q *Queries) InsertOutboundClick(ctx context.Context, arg InsertOutboundClickParams) error {
	_, err := q.db.Exec(ctx, insertOutboundClick,
		arg.ID,
		arg.Ts,
		arg.FromPath,
		arg.PageID,
		arg.Locale,
		arg.ReleaseLabel,
		arg.Target,
		arg.VisitorKind,
		arg.BotName,
		arg.Verified,
		arg.VisitorID,
		arg.DailyHash,
		arg.Internal,
		arg.Country,
	)
	return err
}
