// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integrations.sql

package queries

import (
	"context"
	"time"
)

const claimSync = `-- name: ClaimSync :one
UPDATE integrations SET running_since = $1::timestamptz
WHERE kind = $2 AND (running_since IS NULL OR running_since < $3::timestamptz)
RETURNING kind
`

type ClaimSyncParams struct {
	Now         time.Time
	Kind        string
	StaleBefore time.Time
}

// One sync per kind at a time, across processes; a claim older than stale_before is abandoned.
func (q *Queries) ClaimSync(ctx context.Context, arg ClaimSyncParams) (string, error) {
	row := q.db.QueryRow(ctx, claimSync, arg.Now, arg.Kind, arg.StaleBefore)
	var kind string
	err := row.Scan(&kind)
	return kind, err
}

const clearCredential = `-- name: ClearCredential :exec
UPDATE integrations
SET credential = NULL, key_id = NULL, fingerprint = NULL, account = '', target = '', enabled = true, meta = '{}',
    created_by_sub = NULL, created_by_name = NULL, created_at = NULL,
    updated_by_sub = $1::text, updated_by_name = $2::text, updated_at = now(),
    last_sync_at = NULL, last_success_at = NULL, last_error = NULL, last_error_code = NULL,
    next_sync_at = now(), running_since = NULL, backfilled_at = NULL
WHERE kind = $3
`

type ClearCredentialParams struct {
	ActorSub  string
	ActorName string
	Kind      string
}

// Removing a credential resets the row to a bare status row, so a Vault source starts clean.
func (q *Queries) ClearCredential(ctx context.Context, arg ClearCredentialParams) error {
	_, err := q.db.Exec(ctx, clearCredential, arg.ActorSub, arg.ActorName, arg.Kind)
	return err
}

const cloudflareDaily = `-- name: CloudflareDaily :many
SELECT day, dimension, value, requests FROM cloudflare_daily
WHERE host = $1 AND day >= $2 AND day < $3
ORDER BY day, dimension, requests DESC
`

type CloudflareDailyParams struct {
	Host    string
	FromDay time.Time
	ToDay   time.Time
}

type CloudflareDailyRow struct {
	Day       time.Time
	Dimension string
	Value     string
	Requests  int64
}

func (q *Queries) CloudflareDaily(ctx context.Context, arg CloudflareDailyParams) ([]CloudflareDailyRow, error) {
	rows, err := q.db.Query(ctx, cloudflareDaily, arg.Host, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CloudflareDailyRow{}
	for rows.Next() {
		var i CloudflareDailyRow
		if err := rows.Scan(
			&i.Day,
			&i.Dimension,
			&i.Value,
			&i.Requests,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cloudflareRowCount = `-- name: CloudflareRowCount :one
SELECT count(*) FROM cloudflare_daily WHERE host = $1
`

func (q *Queries) CloudflareRowCount(ctx context.Context, host string) (int64, error) {
	row := q.db.QueryRow(ctx, cloudflareRowCount, host)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const ensureIntegration = `-- name: EnsureIntegration :exec
INSERT INTO integrations (kind) VALUES ($1) ON CONFLICT (kind) DO NOTHING
`

func (q *Queries) EnsureIntegration(ctx context.Context, kind string) error {
	_, err := q.db.Exec(ctx, ensureIntegration, kind)
	return err
}

const finishSync = `-- name: FinishSync :exec
UPDATE integrations
SET running_since = NULL, last_sync_at = now(),
    last_success_at = CASE WHEN $1::boolean THEN now() ELSE last_success_at END,
    last_error = $2, last_error_code = $3,
    next_sync_at = $4::timestamptz,
    backfilled_at = CASE WHEN $1::boolean AND backfilled_at IS NULL THEN now() ELSE backfilled_at END
WHERE kind = $5
`

type FinishSyncParams struct {
	Ok            bool
	LastError     *string
	LastErrorCode *string
	NextSyncAt    *time.Time
	Kind          string
}

func (q *Queries) FinishSync(ctx context.Context, arg FinishSyncParams) error {
	_, err := q.db.Exec(ctx, finishSync,
		arg.Ok,
		arg.LastError,
		arg.LastErrorCode,
		arg.NextSyncAt,
		arg.Kind,
	)
	return err
}

const getIntegration = `-- name: GetIntegration :one
SELECT kind, credential, key_id, fingerprint, account, target, enabled, meta, created_by_sub, created_by_name, created_at, updated_by_sub, updated_by_name, updated_at, last_sync_at, last_success_at, last_error, last_error_code, next_sync_at, running_since, backfilled_at FROM integrations WHERE kind = $1
`

func (q *Queries) GetIntegration(ctx context.Context, kind string) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegration, kind)
	var i Integration
	err := row.Scan(
		&i.Kind,
		&i.Credential,
		&i.KeyID,
		&i.Fingerprint,
		&i.Account,
		&i.Target,
		&i.Enabled,
		&i.Meta,
		&i.CreatedBySub,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedBySub,
		&i.UpdatedByName,
		&i.UpdatedAt,
		&i.LastSyncAt,
		&i.LastSuccessAt,
		&i.LastError,
		&i.LastErrorCode,
		&i.NextSyncAt,
		&i.RunningSince,
		&i.BackfilledAt,
	)
	return i, err
}

const hitsPerUTCDay = `-- name: HitsPerUTCDay :many
SELECT (ts AT TIME ZONE 'UTC')::date AS day, count(*) AS hits,
       count(*) FILTER (WHERE visitor_kind IN ('ai-crawler', 'ai-fetcher')) AS ai_hits
FROM hits
WHERE ts >= $1 AND ts < $2
GROUP BY 1
ORDER BY 1
`

type HitsPerUTCDayParams struct {
	FromTs time.Time
	ToTs   time.Time
}

type HitsPerUTCDayRow struct {
	Day    time.Time
	Hits   int64
	AiHits int64
}

func (q *Queries) HitsPerUTCDay(ctx context.Context, arg HitsPerUTCDayParams) ([]HitsPerUTCDayRow, error) {
	rows, err := q.db.Query(ctx, hitsPerUTCDay, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HitsPerUTCDayRow{}
	for rows.Next() {
		var i HitsPerUTCDayRow
		if err := rows.Scan(&i.Day, &i.Hits, &i.AiHits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertIntegrationEvent = `-- name: InsertIntegrationEvent :exec
INSERT INTO integration_events (kind, action, ok, code, detail, count, http_status, actor_sub, actor_name)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9::text)
`

type InsertIntegrationEventParams struct {
	Kind       string
	Action     string
	Ok         bool
	Code       string
	Detail     string
	Count      *int64
	HttpStatus *int64
	ActorSub   *string
	ActorName  string
}

func (q *Queries) InsertIntegrationEvent(ctx context.Context, arg InsertIntegrationEventParams) error {
	_, err := q.db.Exec(ctx, insertIntegrationEvent,
		arg.Kind,
		arg.Action,
		arg.Ok,
		arg.Code,
		arg.Detail,
		arg.Count,
		arg.HttpStatus,
		arg.ActorSub,
		arg.ActorName,
	)
	return err
}

const listIntegrationEvents = `-- name: ListIntegrationEvents :many
SELECT id, kind, action, ok, code, detail, count, http_status, actor_sub, actor_name, at FROM integration_events WHERE kind = $1 ORDER BY at DESC, id DESC LIMIT $2
`

type ListIntegrationEventsParams struct {
	Kind string
	Lim  int32
}

func (q *Queries) ListIntegrationEvents(ctx context.Context, arg ListIntegrationEventsParams) ([]IntegrationEvent, error) {
	rows, err := q.db.Query(ctx, listIntegrationEvents, arg.Kind, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntegrationEvent{}
	for rows.Next() {
		var i IntegrationEvent
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Action,
			&i.Ok,
			&i.Code,
			&i.Detail,
			&i.Count,
			&i.HttpStatus,
			&i.ActorSub,
			&i.ActorName,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrations = `-- name: ListIntegrations :many
SELECT kind, credential, key_id, fingerprint, account, target, enabled, meta, created_by_sub, created_by_name, created_at, updated_by_sub, updated_by_name, updated_at, last_sync_at, last_success_at, last_error, last_error_code, next_sync_at, running_since, backfilled_at FROM integrations ORDER BY kind
`

func (q *Queries) ListIntegrations(ctx context.Context) ([]Integration, error) {
	rows, err := q.db.Query(ctx, listIntegrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Integration{}
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.Kind,
			&i.Credential,
			&i.KeyID,
			&i.Fingerprint,
			&i.Account,
			&i.Target,
			&i.Enabled,
			&i.Meta,
			&i.CreatedBySub,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedBySub,
			&i.UpdatedByName,
			&i.UpdatedAt,
			&i.LastSyncAt,
			&i.LastSuccessAt,
			&i.LastError,
			&i.LastErrorCode,
			&i.NextSyncAt,
			&i.RunningSince,
			&i.BackfilledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifiedURLCount = `-- name: NotifiedURLCount :one
SELECT COALESCE(sum(count), 0)::bigint FROM integration_events WHERE kind = 'indexnow' AND action = 'notify' AND ok
`

func (q *Queries) NotifiedURLCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, notifiedURLCount)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const originAIBots = `-- name: OriginAIBots :many
SELECT COALESCE(bot_name, '')::text AS bot_name, count(*) AS hits
FROM hits
WHERE ts >= $1 AND ts < $2 AND visitor_kind IN ('ai-crawler', 'ai-fetcher')
GROUP BY 1
ORDER BY 2 DESC
`

type OriginAIBotsParams struct {
	FromTs time.Time
	ToTs   time.Time
}

type OriginAIBotsRow struct {
	BotName string
	Hits    int64
}

func (q *Queries) OriginAIBots(ctx context.Context, arg OriginAIBotsParams) ([]OriginAIBotsRow, error) {
	rows, err := q.db.Query(ctx, originAIBots, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OriginAIBotsRow{}
	for rows.Next() {
		var i OriginAIBotsRow
		if err := rows.Scan(&i.BotName, &i.Hits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordError = `-- name: RecordError :exec
UPDATE integrations SET last_error = $1, last_error_code = $2 WHERE kind = $3
`

type RecordErrorParams struct {
	LastError     *string
	LastErrorCode *string
	Kind          string
}

func (q *Queries) RecordError(ctx context.Context, arg RecordErrorParams) error {
	_, err := q.db.Exec(ctx, recordError, arg.LastError, arg.LastErrorCode, arg.Kind)
	return err
}

const saveCredential = `-- name: SaveCredential :exec
INSERT INTO integrations (
    kind, credential, key_id, fingerprint, account, target, enabled, meta,
    created_by_sub, created_by_name, created_at, updated_by_sub, updated_by_name, updated_at, next_sync_at
)
VALUES (
    $1, $2, $3::text, $4::text, $5, $6, true, '{}',
    $7::text, $8::text, now(), $7::text, $8::text, now(), now()
)
ON CONFLICT (kind) DO UPDATE
SET credential = excluded.credential, key_id = excluded.key_id, fingerprint = excluded.fingerprint,
    account = excluded.account, target = excluded.target, enabled = true, meta = '{}',
    created_by_sub = CASE WHEN integrations.credential IS NULL THEN excluded.created_by_sub ELSE integrations.created_by_sub END,
    created_by_name = CASE WHEN integrations.credential IS NULL THEN excluded.created_by_name ELSE integrations.created_by_name END,
    created_at = CASE WHEN integrations.credential IS NULL THEN excluded.created_at ELSE integrations.created_at END,
    updated_by_sub = excluded.updated_by_sub, updated_by_name = excluded.updated_by_name, updated_at = now(),
    last_sync_at = NULL, last_success_at = NULL, last_error = NULL, last_error_code = NULL,
    next_sync_at = now(), backfilled_at = NULL
`

type SaveCredentialParams struct {
	Kind        string
	Credential  []byte
	KeyID       string
	Fingerprint string
	Account     string
	Target      string
	ActorSub    string
	ActorName   string
}

// A new credential restarts the sync state, so the next run backfills.
func (q *Queries) SaveCredential(ctx context.Context, arg SaveCredentialParams) error {
	_, err := q.db.Exec(ctx, saveCredential,
		arg.Kind,
		arg.Credential,
		arg.KeyID,
		arg.Fingerprint,
		arg.Account,
		arg.Target,
		arg.ActorSub,
		arg.ActorName,
	)
	return err
}

const searchRowCounts = `-- name: SearchRowCounts :many
SELECT source, count(*) AS n FROM search_performance GROUP BY source
`

type SearchRowCountsRow struct {
	Source string
	N      int64
}

func (q *Queries) SearchRowCounts(ctx context.Context) ([]SearchRowCountsRow, error) {
	rows, err := q.db.Query(ctx, searchRowCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchRowCountsRow{}
	for rows.Next() {
		var i SearchRowCountsRow
		if err := rows.Scan(&i.Source, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEnabled = `-- name: SetEnabled :exec
UPDATE integrations
SET enabled = $1, updated_by_sub = $2::text, updated_by_name = $3::text, updated_at = now()
WHERE kind = $4
`

type SetEnabledParams struct {
	Enabled   bool
	ActorSub  string
	ActorName string
	Kind      string
}

func (q *Queries) SetEnabled(ctx context.Context, arg SetEnabledParams) error {
	_, err := q.db.Exec(ctx, setEnabled,
		arg.Enabled,
		arg.ActorSub,
		arg.ActorName,
		arg.Kind,
	)
	return err
}

const setMeta = `-- name: SetMeta :exec
UPDATE integrations SET meta = $1 WHERE kind = $2
`

type SetMetaParams struct {
	Meta []byte
	Kind string
}

func (q *Queries) SetMeta(ctx context.Context, arg SetMetaParams) error {
	_, err := q.db.Exec(ctx, setMeta, arg.Meta, arg.Kind)
	return err
}

const setTarget = `-- name: SetTarget :exec
INSERT INTO integrations (kind, target, updated_by_sub, updated_by_name, updated_at, next_sync_at)
VALUES ($1, $2, $3::text, $4::text, now(), now())
ON CONFLICT (kind) DO UPDATE
SET target = excluded.target, updated_by_sub = excluded.updated_by_sub, updated_by_name = excluded.updated_by_name,
    updated_at = now(), next_sync_at = now(), backfilled_at = NULL, last_error = NULL, last_error_code = NULL
`

type SetTargetParams struct {
	Kind      string
	Target    string
	ActorSub  string
	ActorName string
}

func (q *Queries) SetTarget(ctx context.Context, arg SetTargetParams) error {
	_, err := q.db.Exec(ctx, setTarget,
		arg.Kind,
		arg.Target,
		arg.ActorSub,
		arg.ActorName,
	)
	return err
}

const upsertCloudflareDaily = `-- name: UpsertCloudflareDaily :exec
INSERT INTO cloudflare_daily (host, day, dimension, value, requests, imported_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (host, day, dimension, value) DO UPDATE SET requests = excluded.requests, imported_at = now()
`

type UpsertCloudflareDailyParams struct {
	Host      string
	Day       time.Time
	Dimension string
	Value     string
	Requests  int64
}

func (q *Queries) UpsertCloudflareDaily(ctx context.Context, arg UpsertCloudflareDailyParams) error {
	_, err := q.db.Exec(ctx, upsertCloudflareDaily,
		arg.Host,
		arg.Day,
		arg.Dimension,
		arg.Value,
		arg.Requests,
	)
	return err
}
