// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"

	"github.com/google/uuid"
)

type Hit struct {
	ID              uuid.UUID
	Ts              time.Time
	Path            string
	PageID          *string
	Locale          *string
	ReleaseLabel    string
	Format          string
	Status          int64
	VisitorKind     string
	BotName         *string
	Verified        *bool
	ArrivalChannel  *string
	ReferrerHost    *string
	ReferrerName    *string
	UtmSource       *string
	UtmMedium       *string
	UtmCampaign     *string
	UtmTerm         *string
	UtmContent      *string
	Country         *string
	UserAgent       string
	VisitorID       *string
	DailyHash       string
	Internal        bool
	BeaconConfirmed bool
	EngagedMs       *int64
	Resource        string
	AppVersion      string
}

type OutboundClick struct {
	ID           uuid.UUID
	Ts           time.Time
	FromPath     string
	PageID       *string
	Locale       *string
	ReleaseLabel string
	Target       string
	VisitorKind  string
	BotName      *string
	Verified     *bool
	VisitorID    *string
	DailyHash    string
	Internal     bool
	Country      *string
	AppVersion   string
}

type Page struct {
	ReleaseLabel string
	Path         string
	PageID       string
	Locale       string
	Type         string
	Title        string
	Description  string
	H1           string
	Keywords     []string
	WordCount    int64
	ContentHash  string
}

type Release struct {
	Label       string
	Note        string
	ContentHash string
	FirstSeenAt time.Time
	LastSeenAt  time.Time
	AppVersion  string
	AppVersions []string
	Tags        []string
}

type SearchPerformance struct {
	Source      string
	Day         time.Time
	Page        string
	Path        string
	Query       string
	Clicks      int64
	Impressions int64
	Ctr         float64
	Position    float64
	ImportedAt  time.Time
}
