// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID             int64
	Issuer         string
	Sub            string
	Name           string
	Email          string
	Roles          []string
	Admin          bool
	CreatedAt      time.Time
	LastLoginAt    time.Time
	RolesCheckedAt time.Time
}

type CloudflareDaily struct {
	Host       string
	Day        time.Time
	Dimension  string
	Value      string
	Requests   int64
	ImportedAt time.Time
}

type Hit struct {
	ID              uuid.UUID
	Ts              time.Time
	Path            string
	PageID          *string
	Locale          *string
	ReleaseLabel    string
	Format          string
	Status          int64
	VisitorKind     string
	BotName         *string
	Verified        *bool
	ArrivalChannel  *string
	ReferrerHost    *string
	ReferrerName    *string
	UtmSource       *string
	UtmMedium       *string
	UtmCampaign     *string
	UtmTerm         *string
	UtmContent      *string
	Country         *string
	UserAgent       string
	VisitorID       *string
	DailyHash       string
	Internal        bool
	BeaconConfirmed bool
	EngagedMs       *int64
	Resource        string
	AppVersion      string
}

type Integration struct {
	Kind          string
	Credential    []byte
	KeyID         *string
	Fingerprint   *string
	Account       string
	Target        string
	Enabled       bool
	Meta          []byte
	CreatedBySub  *string
	CreatedByName *string
	CreatedAt     *time.Time
	UpdatedBySub  *string
	UpdatedByName *string
	UpdatedAt     *time.Time
	LastSyncAt    *time.Time
	LastSuccessAt *time.Time
	LastError     *string
	LastErrorCode *string
	NextSyncAt    *time.Time
	RunningSince  *time.Time
	BackfilledAt  *time.Time
}

type IntegrationEvent struct {
	ID         int64
	Kind       string
	Action     string
	Ok         bool
	Code       string
	Detail     string
	Count      *int64
	HttpStatus *int64
	ActorSub   *string
	ActorName  string
	At         time.Time
}

type OutboundClick struct {
	ID           uuid.UUID
	Ts           time.Time
	FromPath     string
	PageID       *string
	Locale       *string
	ReleaseLabel string
	Target       string
	VisitorKind  string
	BotName      *string
	Verified     *bool
	VisitorID    *string
	DailyHash    string
	Internal     bool
	Country      *string
	AppVersion   string
}

type Page struct {
	ReleaseLabel string
	Path         string
	PageID       string
	Locale       string
	Type         string
	Title        string
	Description  string
	H1           string
	Keywords     []string
	WordCount    int64
	ContentHash  string
}

type Release struct {
	Label       string
	Note        string
	ContentHash string
	FirstSeenAt time.Time
	LastSeenAt  time.Time
	AppVersion  string
	AppVersions []string
	Tags        []string
}

type SearchPerformance struct {
	Source      string
	Day         time.Time
	Page        string
	Path        string
	Query       string
	Clicks      int64
	Impressions int64
	Ctr         float64
	Position    float64
	ImportedAt  time.Time
}

type Session struct {
	ID             string
	AccountID      int64
	RefreshToken   []byte
	KeyID          string
	UserAgent      string
	CreatedAt      time.Time
	LastSeenAt     time.Time
	RolesCheckedAt time.Time
	ExpiresAt      time.Time
}
