// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: releases.sql

package queries

import (
	"context"
	"time"
)

const listPages = `-- name: ListPages :many
SELECT release_label, path, page_id, locale, type, title, description, h1, keywords, word_count, content_hash FROM pages ORDER BY release_label, path
`

func (q *Queries) ListPages(ctx context.Context) ([]Page, error) {
	rows, err := q.db.Query(ctx, listPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ReleaseLabel,
			&i.Path,
			&i.PageID,
			&i.Locale,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.H1,
			&i.Keywords,
			&i.WordCount,
			&i.ContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleases = `-- name: ListReleases :many
SELECT label, note, content_hash, first_seen_at, last_seen_at FROM releases ORDER BY first_seen_at, label
`

func (q *Queries) ListReleases(ctx context.Context) ([]Release, error) {
	rows, err := q.db.Query(ctx, listReleases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Release{}
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.Label,
			&i.Note,
			&i.ContentHash,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageLastMod = `-- name: PageLastMod :many
SELECT cur.path, min(r.first_seen_at)::timestamptz AS since
FROM pages AS cur
JOIN pages AS p ON p.path = cur.path AND p.content_hash = cur.content_hash
JOIN releases AS r ON r.label = p.release_label
WHERE cur.release_label = $1
GROUP BY cur.path
`

type PageLastModRow struct {
	Path  string
	Since time.Time
}

func (q *Queries) PageLastMod(ctx context.Context, releaseLabel string) ([]PageLastModRow, error) {
	rows, err := q.db.Query(ctx, pageLastMod, releaseLabel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PageLastModRow{}
	for rows.Next() {
		var i PageLastModRow
		if err := rows.Scan(&i.Path, &i.Since); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPage = `-- name: UpsertPage :exec
INSERT INTO pages (release_label, path, page_id, locale, type, title, description, h1, keywords, word_count, content_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (release_label, path) DO UPDATE
SET page_id = excluded.page_id, locale = excluded.locale, type = excluded.type, title = excluded.title,
    description = excluded.description, h1 = excluded.h1, keywords = excluded.keywords,
    word_count = excluded.word_count, content_hash = excluded.content_hash
`

type UpsertPageParams struct {
	ReleaseLabel string
	Path         string
	PageID       string
	Locale       string
	Type         string
	Title        string
	Description  string
	H1           string
	Keywords     []string
	WordCount    int64
	ContentHash  string
}

func (q *Queries) UpsertPage(ctx context.Context, arg UpsertPageParams) error {
	_, err := q.db.Exec(ctx, upsertPage,
		arg.ReleaseLabel,
		arg.Path,
		arg.PageID,
		arg.Locale,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.H1,
		arg.Keywords,
		arg.WordCount,
		arg.ContentHash,
	)
	return err
}

const upsertRelease = `-- name: UpsertRelease :one
INSERT INTO releases (label, note, content_hash)
VALUES ($1, $2, $3)
ON CONFLICT (label) DO UPDATE
SET note = excluded.note, content_hash = excluded.content_hash, last_seen_at = now()
RETURNING first_seen_at
`

type UpsertReleaseParams struct {
	Label       string
	Note        string
	ContentHash string
}

func (q *Queries) UpsertRelease(ctx context.Context, arg UpsertReleaseParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, upsertRelease, arg.Label, arg.Note, arg.ContentHash)
	var first_seen_at time.Time
	err := row.Scan(&first_seen_at)
	return first_seen_at, err
}
