// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: releases.sql

package queries

import (
	"context"
	"time"
)

const appVersions = `-- name: AppVersions :many
SELECT DISTINCT unnest(app_versions)::text AS app_version FROM releases ORDER BY 1
`

func (q *Queries) AppVersions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, appVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var app_version string
		if err := rows.Scan(&app_version); err != nil {
			return nil, err
		}
		items = append(items, app_version)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestRelease = `-- name: LatestRelease :one
SELECT label FROM releases ORDER BY last_seen_at DESC, first_seen_at DESC LIMIT 1
`

// The release the previous process served: the most recently seen one.
func (q *Queries) LatestRelease(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, latestRelease)
	var label string
	err := row.Scan(&label)
	return label, err
}

const listPages = `-- name: ListPages :many
SELECT release_label, path, page_id, locale, type, title, description, h1, keywords, word_count, content_hash FROM pages ORDER BY release_label, path
`

func (q *Queries) ListPages(ctx context.Context) ([]Page, error) {
	rows, err := q.db.Query(ctx, listPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ReleaseLabel,
			&i.Path,
			&i.PageID,
			&i.Locale,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.H1,
			&i.Keywords,
			&i.WordCount,
			&i.ContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleases = `-- name: ListReleases :many
SELECT label, note, content_hash, first_seen_at, last_seen_at, app_version, app_versions, tags FROM releases ORDER BY first_seen_at, label
`

func (q *Queries) ListReleases(ctx context.Context) ([]Release, error) {
	rows, err := q.db.Query(ctx, listReleases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Release{}
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.Label,
			&i.Note,
			&i.ContentHash,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.AppVersion,
			&i.AppVersions,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageLastMod = `-- name: PageLastMod :many
SELECT cur.path, min(r.first_seen_at)::timestamptz AS since
FROM pages AS cur
JOIN pages AS p ON p.path = cur.path AND p.content_hash = cur.content_hash
JOIN releases AS r ON r.label = p.release_label
WHERE cur.release_label = $1
GROUP BY cur.path
`

type PageLastModRow struct {
	Path  string
	Since time.Time
}

func (q *Queries) PageLastMod(ctx context.Context, releaseLabel string) ([]PageLastModRow, error) {
	rows, err := q.db.Query(ctx, pageLastMod, releaseLabel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PageLastModRow{}
	for rows.Next() {
		var i PageLastModRow
		if err := rows.Scan(&i.Path, &i.Since); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releasePageHashes = `-- name: ReleasePageHashes :many
SELECT path, content_hash FROM pages WHERE release_label = $1 ORDER BY path
`

type ReleasePageHashesRow struct {
	Path        string
	ContentHash string
}

func (q *Queries) ReleasePageHashes(ctx context.Context, releaseLabel string) ([]ReleasePageHashesRow, error) {
	rows, err := q.db.Query(ctx, releasePageHashes, releaseLabel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReleasePageHashesRow{}
	for rows.Next() {
		var i ReleasePageHashesRow
		if err := rows.Scan(&i.Path, &i.ContentHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseTags = `-- name: ReleaseTags :many
SELECT DISTINCT unnest(tags)::text AS tag FROM releases ORDER BY 1
`

func (q *Queries) ReleaseTags(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, releaseTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPage = `-- name: UpsertPage :exec
INSERT INTO pages (release_label, path, page_id, locale, type, title, description, h1, keywords, word_count, content_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (release_label, path) DO UPDATE
SET page_id = excluded.page_id, locale = excluded.locale, type = excluded.type, title = excluded.title,
    description = excluded.description, h1 = excluded.h1, keywords = excluded.keywords,
    word_count = excluded.word_count, content_hash = excluded.content_hash
`

type UpsertPageParams struct {
	ReleaseLabel string
	Path         string
	PageID       string
	Locale       string
	Type         string
	Title        string
	Description  string
	H1           string
	Keywords     []string
	WordCount    int64
	ContentHash  string
}

func (q *Queries) UpsertPage(ctx context.Context, arg UpsertPageParams) error {
	_, err := q.db.Exec(ctx, upsertPage,
		arg.ReleaseLabel,
		arg.Path,
		arg.PageID,
		arg.Locale,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.H1,
		arg.Keywords,
		arg.WordCount,
		arg.ContentHash,
	)
	return err
}

const upsertRelease = `-- name: UpsertRelease :one
INSERT INTO releases (label, note, content_hash, app_version, app_versions, tags)
VALUES ($1, $2, $3, $4::text, ARRAY[$4::text], $5::text [])
ON CONFLICT (label) DO UPDATE
SET note = excluded.note, content_hash = excluded.content_hash, tags = excluded.tags, last_seen_at = now(),
    app_version = CASE WHEN releases.app_version = '' THEN excluded.app_version ELSE releases.app_version END,
    app_versions = CASE
        WHEN excluded.app_version = ANY (releases.app_versions) THEN releases.app_versions
        ELSE releases.app_versions || excluded.app_version
    END
RETURNING first_seen_at
`

type UpsertReleaseParams struct {
	Label       string
	Note        string
	ContentHash string
	AppVersion  string
	Tags        []string
}

// app_version is the build that first published the release; app_versions every build that served it.
func (q *Queries) UpsertRelease(ctx context.Context, arg UpsertReleaseParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, upsertRelease,
		arg.Label,
		arg.Note,
		arg.ContentHash,
		arg.AppVersion,
		arg.Tags,
	)
	var first_seen_at time.Time
	err := row.Scan(&first_seen_at)
	return first_seen_at, err
}
