// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package queries

import (
	"context"
	"time"
)

const listOutboundClicks = `-- name: ListOutboundClicks :many
SELECT id, ts, from_path, page_id, locale, release_label, target, visitor_kind, bot_name, verified, visitor_id, daily_hash, internal, country FROM outbound_clicks ORDER BY ts
`

func (q *Queries) ListOutboundClicks(ctx context.Context) ([]OutboundClick, error) {
	rows, err := q.db.Query(ctx, listOutboundClicks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboundClick{}
	for rows.Next() {
		var i OutboundClick
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.FromPath,
			&i.PageID,
			&i.Locale,
			&i.ReleaseLabel,
			&i.Target,
			&i.VisitorKind,
			&i.BotName,
			&i.Verified,
			&i.VisitorID,
			&i.DailyHash,
			&i.Internal,
			&i.Country,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSearchPerformance = `-- name: ListSearchPerformance :many
SELECT source, day, page, path, query, clicks, impressions, ctr, position, imported_at FROM search_performance ORDER BY day, source, page, query
`

func (q *Queries) ListSearchPerformance(ctx context.Context) ([]SearchPerformance, error) {
	rows, err := q.db.Query(ctx, listSearchPerformance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPerformance{}
	for rows.Next() {
		var i SearchPerformance
		if err := rows.Scan(
			&i.Source,
			&i.Day,
			&i.Page,
			&i.Path,
			&i.Query,
			&i.Clicks,
			&i.Impressions,
			&i.Ctr,
			&i.Position,
			&i.ImportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByPath = `-- name: SearchByPath :many
SELECT path, COALESCE(sum(clicks), 0)::bigint AS clicks, COALESCE(sum(impressions), 0)::bigint AS impressions,
       COALESCE(sum(position * impressions) / NULLIF(sum(impressions), 0), 0)::double precision AS avg_position
FROM search_performance
WHERE day >= $1 AND day < $2
GROUP BY path
`

type SearchByPathParams struct {
	FromDay time.Time
	ToDay   time.Time
}

type SearchByPathRow struct {
	Path        string
	Clicks      int64
	Impressions int64
	AvgPosition float64
}

func (q *Queries) SearchByPath(ctx context.Context, arg SearchByPathParams) ([]SearchByPathRow, error) {
	rows, err := q.db.Query(ctx, searchByPath, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchByPathRow{}
	for rows.Next() {
		var i SearchByPathRow
		if err := rows.Scan(
			&i.Path,
			&i.Clicks,
			&i.Impressions,
			&i.AvgPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDaily = `-- name: SearchDaily :many
SELECT day, COALESCE(sum(clicks), 0)::bigint AS clicks, COALESCE(sum(impressions), 0)::bigint AS impressions
FROM search_performance
WHERE day >= $1 AND day < $2
  AND ($3::text IS NULL OR path = $3)
GROUP BY day
ORDER BY day
`

type SearchDailyParams struct {
	FromDay time.Time
	ToDay   time.Time
	Path    *string
}

type SearchDailyRow struct {
	Day         time.Time
	Clicks      int64
	Impressions int64
}

func (q *Queries) SearchDaily(ctx context.Context, arg SearchDailyParams) ([]SearchDailyRow, error) {
	rows, err := q.db.Query(ctx, searchDaily, arg.FromDay, arg.ToDay, arg.Path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDailyRow{}
	for rows.Next() {
		var i SearchDailyRow
		if err := rows.Scan(&i.Day, &i.Clicks, &i.Impressions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTotals = `-- name: SearchTotals :many
SELECT source, COALESCE(sum(clicks), 0)::bigint AS clicks, COALESCE(sum(impressions), 0)::bigint AS impressions,
       COALESCE(sum(position * impressions) / NULLIF(sum(impressions), 0), 0)::double precision AS avg_position
FROM search_performance
WHERE day >= $1 AND day < $2
  AND ($3::text IS NULL OR path = $3)
GROUP BY source
ORDER BY source
`

type SearchTotalsParams struct {
	FromDay time.Time
	ToDay   time.Time
	Path    *string
}

type SearchTotalsRow struct {
	Source      string
	Clicks      int64
	Impressions int64
	AvgPosition float64
}

func (q *Queries) SearchTotals(ctx context.Context, arg SearchTotalsParams) ([]SearchTotalsRow, error) {
	rows, err := q.db.Query(ctx, searchTotals, arg.FromDay, arg.ToDay, arg.Path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTotalsRow{}
	for rows.Next() {
		var i SearchTotalsRow
		if err := rows.Scan(
			&i.Source,
			&i.Clicks,
			&i.Impressions,
			&i.AvgPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topQueries = `-- name: TopQueries :many
SELECT query, source, COALESCE(sum(clicks), 0)::bigint AS clicks, COALESCE(sum(impressions), 0)::bigint AS impressions,
       COALESCE(sum(position * impressions) / NULLIF(sum(impressions), 0), 0)::double precision AS avg_position
FROM search_performance
WHERE day >= $1 AND day < $2
  AND ($3::text IS NULL OR path = $3)
GROUP BY query, source
ORDER BY impressions DESC, clicks DESC
LIMIT 50
`

type TopQueriesParams struct {
	FromDay time.Time
	ToDay   time.Time
	Path    *string
}

type TopQueriesRow struct {
	Query       string
	Source      string
	Clicks      int64
	Impressions int64
	AvgPosition float64
}

func (q *Queries) TopQueries(ctx context.Context, arg TopQueriesParams) ([]TopQueriesRow, error) {
	rows, err := q.db.Query(ctx, topQueries, arg.FromDay, arg.ToDay, arg.Path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopQueriesRow{}
	for rows.Next() {
		var i TopQueriesRow
		if err := rows.Scan(
			&i.Query,
			&i.Source,
			&i.Clicks,
			&i.Impressions,
			&i.AvgPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSearchPerformance = `-- name: UpsertSearchPerformance :exec
INSERT INTO search_performance (source, day, page, path, query, clicks, impressions, ctr, position, imported_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
ON CONFLICT (source, day, page, query) DO UPDATE
SET path = excluded.path, clicks = excluded.clicks, impressions = excluded.impressions,
    ctr = excluded.ctr, position = excluded.position, imported_at = now()
`

type UpsertSearchPerformanceParams struct {
	Source      string
	Day         time.Time
	Page        string
	Path        string
	Query       string
	Clicks      int64
	Impressions int64
	Ctr         float64
	Position    float64
}

func (q *Queries) UpsertSearchPerformance(ctx context.Context, arg UpsertSearchPerformanceParams) error {
	_, err := q.db.Exec(ctx, upsertSearchPerformance,
		arg.Source,
		arg.Day,
		arg.Page,
		arg.Path,
		arg.Query,
		arg.Clicks,
		arg.Impressions,
		arg.Ctr,
		arg.Position,
	)
	return err
}
