// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package queries

import (
	"context"
	"time"
)

const agentTopPaths = `-- name: AgentTopPaths :many
SELECT path, count(*) AS hits,
       count(*) FILTER (WHERE visitor_kind = 'ai-crawler') AS ai_crawler,
       count(*) FILTER (WHERE visitor_kind = 'ai-fetcher') AS ai_fetcher,
       count(*) FILTER (WHERE visitor_kind = 'search-crawler') AS search_crawler
FROM hits
WHERE ts >= $1 AND ts < $2
  AND ($3::text IS NULL OR locale = $3)
  AND ($4::text IS NULL OR release_label = $4)
  AND visitor_kind IN ('ai-crawler', 'ai-fetcher', 'search-crawler')
GROUP BY path
ORDER BY hits DESC
LIMIT 50
`

type AgentTopPathsParams struct {
	FromTs  time.Time
	ToTs    time.Time
	Locale  *string
	Release *string
}

type AgentTopPathsRow struct {
	Path          string
	Hits          int64
	AiCrawler     int64
	AiFetcher     int64
	SearchCrawler int64
}

func (q *Queries) AgentTopPaths(ctx context.Context, arg AgentTopPathsParams) ([]AgentTopPathsRow, error) {
	rows, err := q.db.Query(ctx, agentTopPaths,
		arg.FromTs,
		arg.ToTs,
		arg.Locale,
		arg.Release,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTopPathsRow{}
	for rows.Next() {
		var i AgentTopPathsRow
		if err := rows.Scan(
			&i.Path,
			&i.Hits,
			&i.AiCrawler,
			&i.AiFetcher,
			&i.SearchCrawler,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const botTable = `-- name: BotTable :many
SELECT COALESCE(bot_name, '')::text AS bot_name, visitor_kind, COALESCE(verified, false)::boolean AS verified,
       count(*) AS hits, count(DISTINCT path) AS paths,
       count(*) FILTER (WHERE format = 'md') AS markdown, count(*) FILTER (WHERE format = 'txt') AS txt,
       count(*) FILTER (WHERE format = 'xml') AS xml, max(ts)::timestamptz AS last_seen
FROM hits
WHERE ts >= $1 AND ts < $2
  AND ($3::text IS NULL OR locale = $3)
  AND ($4::text IS NULL OR release_label = $4)
  AND ($5::text IS NULL OR path = $5)
  AND visitor_kind NOT IN ('human', 'human-unconfirmed')
GROUP BY 1, 2, 3
ORDER BY hits DESC
`

type BotTableParams struct {
	FromTs  time.Time
	ToTs    time.Time
	Locale  *string
	Release *string
	Path    *string
}

type BotTableRow struct {
	BotName     string
	VisitorKind string
	Verified    bool
	Hits        int64
	Paths       int64
	Markdown    int64
	Txt         int64
	Xml         int64
	LastSeen    time.Time
}

func (q *Queries) BotTable(ctx context.Context, arg BotTableParams) ([]BotTableRow, error) {
	rows, err := q.db.Query(ctx, botTable,
		arg.FromTs,
		arg.ToTs,
		arg.Locale,
		arg.Release,
		arg.Path,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BotTableRow{}
	for rows.Next() {
		var i BotTableRow
		if err := rows.Scan(
			&i.BotName,
			&i.VisitorKind,
			&i.Verified,
			&i.Hits,
			&i.Paths,
			&i.Markdown,
			&i.Txt,
			&i.Xml,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelTotals = `-- name: ChannelTotals :many
SELECT COALESCE(arrival_channel, 'direct')::text AS channel, count(*) AS hits,
       count(DISTINCT COALESCE(visitor_id, daily_hash)) AS visitors,
       count(*) FILTER (WHERE beacon_confirmed) AS confirmed
FROM hits
WHERE ts >= $1 AND ts < $2
  AND ($3::text IS NULL OR locale = $3)
  AND ($4::text IS NULL OR release_label = $4)
  AND ($5::boolean OR NOT internal)
  AND visitor_kind IN ('human', 'human-unconfirmed') AND format = 'html'
GROUP BY 1
ORDER BY 2 DESC
`

type ChannelTotalsParams struct {
	FromTs          time.Time
	ToTs            time.Time
	Locale          *string
	Release         *string
	IncludeInternal bool
}

type ChannelTotalsRow struct {
	Channel   string
	Hits      int64
	Visitors  int64
	Confirmed int64
}

func (q *Queries) ChannelTotals(ctx context.Context, arg ChannelTotalsParams) ([]ChannelTotalsRow, error) {
	rows, err := q.db.Query(ctx, channelTotals,
		arg.FromTs,
		arg.ToTs,
		arg.Locale,
		arg.Release,
		arg.IncludeInternal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelTotalsRow{}
	for rows.Next() {
		var i ChannelTotalsRow
		if err := rows.Scan(
			&i.Channel,
			&i.Hits,
			&i.Visitors,
			&i.Confirmed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dailyKinds = `-- name: DailyKinds :many
SELECT (ts AT TIME ZONE 'Europe/Amsterdam')::date AS day, visitor_kind, count(*) AS hits
FROM hits
WHERE ts >= $1 AND ts < $2
  AND ($3::text IS NULL OR locale = $3)
  AND ($4::text IS NULL OR release_label = $4)
  AND ($5::boolean OR NOT internal)
  AND ($6::text IS NULL OR path = $6)
GROUP BY 1, 2
ORDER BY 1, 2
`

type DailyKindsParams struct {
	FromTs          time.Time
	ToTs            time.Time
	Locale          *string
	Release         *string
	IncludeInternal bool
	Path            *string
}

type DailyKindsRow struct {
	Day         time.Time
	VisitorKind string
	Hits        int64
}

func (q *Queries) DailyKinds(ctx context.Context, arg DailyKindsParams) ([]DailyKindsRow, error) {
	rows, err := q.db.Query(ctx, dailyKinds,
		arg.FromTs,
		arg.ToTs,
		arg.Locale,
		arg.Release,
		arg.IncludeInternal,
		arg.Path,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyKindsRow{}
	for rows.Next() {
		var i DailyKindsRow
		if err := rows.Scan(&i.Day, &i.VisitorKind, &i.Hits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const firstTouchChannels = `-- name: FirstTouchChannels :many
WITH first_hits AS (
    SELECT DISTINCT ON (visitor_id) visitor_id, ts, arrival_channel
    FROM hits
    WHERE visitor_id IS NOT NULL AND visitor_kind IN ('human', 'human-unconfirmed')
      AND ($3::boolean OR NOT internal)
    ORDER BY visitor_id, ts
)
SELECT COALESCE(arrival_channel, 'direct')::text AS channel, count(*) AS visitors
FROM first_hits
WHERE ts >= $1 AND ts < $2
GROUP BY 1
ORDER BY 2 DESC
`

type FirstTouchChannelsParams struct {
	FromTs          time.Time
	ToTs            time.Time
	IncludeInternal bool
}

type FirstTouchChannelsRow struct {
	Channel  string
	Visitors int64
}

func (q *Queries) FirstTouchChannels(ctx context.Context, arg FirstTouchChannelsParams) ([]FirstTouchChannelsRow, error) {
	rows, err := q.db.Query(ctx, firstTouchChannels, arg.FromTs, arg.ToTs, arg.IncludeInternal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FirstTouchChannelsRow{}
	for rows.Next() {
		var i FirstTouchChannelsRow
		if err := rows.Scan(&i.Channel, &i.Visitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const kindTotals = `-- name: KindTotals :many

SELECT visitor_kind, count(*) AS hits, count(DISTINCT COALESCE(visitor_id, daily_hash)) AS visitors
FROM hits
WHERE ts >= $1 AND ts < $2
  AND ($3::text IS NULL OR locale = $3)
  AND ($4::text IS NULL OR release_label = $4)
  AND ($5::boolean OR NOT internal)
GROUP BY visitor_kind
ORDER BY visitor_kind
`

type KindTotalsParams struct {
	FromTs          time.Time
	ToTs            time.Time
	Locale          *string
	Release         *string
	IncludeInternal bool
}

type KindTotalsRow struct {
	VisitorKind string
	Hits        int64
	Visitors    int64
}

// Every stats query shares one filter: [from_ts, to_ts), optional locale and release, internal toggle.
func (q *Queries) KindTotals(ctx context.Context, arg KindTotalsParams) ([]KindTotalsRow, error) {
	rows, err := q.db.Query(ctx, kindTotals,
		arg.FromTs,
		arg.ToTs,
		arg.Locale,
		arg.Release,
		arg.IncludeInternal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KindTotalsRow{}
	for rows.Next() {
		var i KindTotalsRow
		if err := rows.Scan(&i.VisitorKind, &i.Hits, &i.Visitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const outboundByPage = `-- name: OutboundByPage :many
SELECT from_path, count(*) AS clicks, count(*) FILTER (WHERE visitor_kind IN ('human', 'human-unconfirmed')) AS human_clicks
FROM outbound_clicks
WHERE ts >= $1 AND ts < $2
  AND ($3::text IS NULL OR locale = $3)
  AND ($4::text IS NULL OR release_label = $4)
  AND ($5::boolean OR NOT internal)
GROUP BY from_path
`

type OutboundByPageParams struct {
	FromTs          time.Time
	ToTs            time.Time
	Locale          *string
	Release         *string
	IncludeInternal bool
}

type OutboundByPageRow struct {
	FromPath    string
	Clicks      int64
	HumanClicks int64
}

func (q *Queries) OutboundByPage(ctx context.Context, arg OutboundByPageParams) ([]OutboundByPageRow, error) {
	rows, err := q.db.Query(ctx, outboundByPage,
		arg.FromTs,
		arg.ToTs,
		arg.Locale,
		arg.Release,
		arg.IncludeInternal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboundByPageRow{}
	for rows.Next() {
		var i OutboundByPageRow
		if err := rows.Scan(&i.FromPath, &i.Clicks, &i.HumanClicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const outboundByRelease = `-- name: OutboundByRelease :many
SELECT release_label, count(*) AS clicks, count(*) FILTER (WHERE visitor_kind IN ('human', 'human-unconfirmed')) AS human_clicks
FROM outbound_clicks
WHERE ts >= $1 AND ts < $2
  AND ($3::text IS NULL OR locale = $3)
  AND ($4::boolean OR NOT internal)
GROUP BY release_label
`

type OutboundByReleaseParams struct {
	FromTs          time.Time
	ToTs            time.Time
	Locale          *string
	IncludeInternal bool
}

type OutboundByReleaseRow struct {
	ReleaseLabel string
	Clicks       int64
	HumanClicks  int64
}

func (q *Queries) OutboundByRelease(ctx context.Context, arg OutboundByReleaseParams) ([]OutboundByReleaseRow, error) {
	rows, err := q.db.Query(ctx, outboundByRelease,
		arg.FromTs,
		arg.ToTs,
		arg.Locale,
		arg.IncludeInternal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboundByReleaseRow{}
	for rows.Next() {
		var i OutboundByReleaseRow
		if err := rows.Scan(&i.ReleaseLabel, &i.Clicks, &i.HumanClicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const outboundTotals = `-- name: OutboundTotals :many
SELECT visitor_kind, count(*) AS clicks
FROM outbound_clicks
WHERE ts >= $1 AND ts < $2
  AND ($3::text IS NULL OR locale = $3)
  AND ($4::text IS NULL OR release_label = $4)
  AND ($5::boolean OR NOT internal)
GROUP BY visitor_kind
ORDER BY visitor_kind
`

type OutboundTotalsParams struct {
	FromTs          time.Time
	ToTs            time.Time
	Locale          *string
	Release         *string
	IncludeInternal bool
}

type OutboundTotalsRow struct {
	VisitorKind string
	Clicks      int64
}

func (q *Queries) OutboundTotals(ctx context.Context, arg OutboundTotalsParams) ([]OutboundTotalsRow, error) {
	rows, err := q.db.Query(ctx, outboundTotals,
		arg.FromTs,
		arg.ToTs,
		arg.Locale,
		arg.Release,
		arg.IncludeInternal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboundTotalsRow{}
	for rows.Next() {
		var i OutboundTotalsRow
		if err := rows.Scan(&i.VisitorKind, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageReferrers = `-- name: PageReferrers :many
SELECT COALESCE(arrival_channel, 'direct')::text AS channel, COALESCE(referrer_host, '')::text AS referrer_host, count(*) AS hits
FROM hits
WHERE ts >= $1 AND ts < $2 AND path = $3
  AND ($4::text IS NULL OR release_label = $4)
  AND ($5::boolean OR NOT internal)
  AND visitor_kind IN ('human', 'human-unconfirmed')
GROUP BY 1, 2
ORDER BY 3 DESC
LIMIT 50
`

type PageReferrersParams struct {
	FromTs          time.Time
	ToTs            time.Time
	Path            string
	Release         *string
	IncludeInternal bool
}

type PageReferrersRow struct {
	Channel      string
	ReferrerHost string
	Hits         int64
}

func (q *Queries) PageReferrers(ctx context.Context, arg PageReferrersParams) ([]PageReferrersRow, error) {
	rows, err := q.db.Query(ctx, pageReferrers,
		arg.FromTs,
		arg.ToTs,
		arg.Path,
		arg.Release,
		arg.IncludeInternal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PageReferrersRow{}
	for rows.Next() {
		var i PageReferrersRow
		if err := rows.Scan(&i.Channel, &i.ReferrerHost, &i.Hits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageTable = `-- name: PageTable :many
SELECT path, max(page_id)::text AS page_id, max(locale)::text AS locale,
       count(*) FILTER (WHERE visitor_kind = 'human') AS human,
       count(*) FILTER (WHERE visitor_kind = 'human-unconfirmed') AS human_unconfirmed,
       count(*) FILTER (WHERE visitor_kind = 'search-crawler') AS search_crawler,
       count(*) FILTER (WHERE visitor_kind = 'ai-crawler') AS ai_crawler,
       count(*) FILTER (WHERE visitor_kind = 'ai-fetcher') AS ai_fetcher,
       count(*) FILTER (WHERE visitor_kind IN ('seo-tool', 'other-bot')) AS other,
       count(*) FILTER (WHERE format = 'md') AS markdown,
       COALESCE(avg(engaged_ms) FILTER (WHERE beacon_confirmed), 0)::bigint AS avg_engaged_ms
FROM hits
WHERE ts >= $1 AND ts < $2
  AND ($3::text IS NULL OR locale = $3)
  AND ($4::text IS NULL OR release_label = $4)
  AND ($5::boolean OR NOT internal)
  AND page_id IS NOT NULL
GROUP BY path
ORDER BY human DESC, human_unconfirmed DESC, path
`

type PageTableParams struct {
	FromTs          time.Time
	ToTs            time.Time
	Locale          *string
	Release         *string
	IncludeInternal bool
}

type PageTableRow struct {
	Path             string
	PageID           string
	Locale           string
	Human            int64
	HumanUnconfirmed int64
	SearchCrawler    int64
	AiCrawler        int64
	AiFetcher        int64
	Other            int64
	Markdown         int64
	AvgEngagedMs     int64
}

func (q *Queries) PageTable(ctx context.Context, arg PageTableParams) ([]PageTableRow, error) {
	rows, err := q.db.Query(ctx, pageTable,
		arg.FromTs,
		arg.ToTs,
		arg.Locale,
		arg.Release,
		arg.IncludeInternal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PageTableRow{}
	for rows.Next() {
		var i PageTableRow
		if err := rows.Scan(
			&i.Path,
			&i.PageID,
			&i.Locale,
			&i.Human,
			&i.HumanUnconfirmed,
			&i.SearchCrawler,
			&i.AiCrawler,
			&i.AiFetcher,
			&i.Other,
			&i.Markdown,
			&i.AvgEngagedMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseTotals = `-- name: ReleaseTotals :many
SELECT release_label,
       count(DISTINCT (ts AT TIME ZONE 'Europe/Amsterdam')::date) AS days,
       count(*) FILTER (WHERE visitor_kind = 'human') AS human,
       count(*) FILTER (WHERE visitor_kind = 'human-unconfirmed') AS human_unconfirmed,
       count(*) FILTER (WHERE visitor_kind = 'search-crawler') AS search_crawler,
       count(*) FILTER (WHERE visitor_kind = 'ai-crawler') AS ai_crawler,
       count(*) FILTER (WHERE visitor_kind = 'ai-fetcher') AS ai_fetcher,
       count(*) FILTER (WHERE visitor_kind IN ('seo-tool', 'other-bot')) AS other,
       count(*) FILTER (WHERE visitor_kind IN ('human', 'human-unconfirmed') AND arrival_channel = 'search') AS from_search,
       count(*) FILTER (WHERE visitor_kind IN ('human', 'human-unconfirmed') AND arrival_channel = 'ai-chat') AS from_ai_chat,
       count(DISTINCT visitor_id) AS visitors
FROM hits
WHERE ts >= $1 AND ts < $2
  AND ($3::text IS NULL OR locale = $3)
  AND ($4::boolean OR NOT internal)
GROUP BY release_label
`

type ReleaseTotalsParams struct {
	FromTs          time.Time
	ToTs            time.Time
	Locale          *string
	IncludeInternal bool
}

type ReleaseTotalsRow struct {
	ReleaseLabel     string
	Days             int64
	Human            int64
	HumanUnconfirmed int64
	SearchCrawler    int64
	AiCrawler        int64
	AiFetcher        int64
	Other            int64
	FromSearch       int64
	FromAiChat       int64
	Visitors         int64
}

func (q *Queries) ReleaseTotals(ctx context.Context, arg ReleaseTotalsParams) ([]ReleaseTotalsRow, error) {
	rows, err := q.db.Query(ctx, releaseTotals,
		arg.FromTs,
		arg.ToTs,
		arg.Locale,
		arg.IncludeInternal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReleaseTotalsRow{}
	for rows.Next() {
		var i ReleaseTotalsRow
		if err := rows.Scan(
			&i.ReleaseLabel,
			&i.Days,
			&i.Human,
			&i.HumanUnconfirmed,
			&i.SearchCrawler,
			&i.AiCrawler,
			&i.AiFetcher,
			&i.Other,
			&i.FromSearch,
			&i.FromAiChat,
			&i.Visitors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const visitorSummary = `-- name: VisitorSummary :one
WITH h AS (
    SELECT visitor_id, daily_hash, (ts AT TIME ZONE 'Europe/Amsterdam')::date AS day
    FROM hits
    WHERE ts >= $1 AND ts < $2
      AND ($3::text IS NULL OR locale = $3)
      AND ($4::text IS NULL OR release_label = $4)
      AND ($5::boolean OR NOT internal)
      AND visitor_kind IN ('human', 'human-unconfirmed')
)
SELECT
    (SELECT count(DISTINCT visitor_id) FROM h WHERE visitor_id IS NOT NULL) AS visitors,
    (SELECT count(*) FROM (
        SELECT visitor_id FROM h WHERE visitor_id IS NOT NULL GROUP BY visitor_id HAVING count(DISTINCT day) > 1
    ) AS r) AS returning_visitors,
    (SELECT count(DISTINCT (daily_hash, day)) FROM h WHERE visitor_id IS NULL) AS daily_visitors
`

type VisitorSummaryParams struct {
	FromTs          time.Time
	ToTs            time.Time
	Locale          *string
	Release         *string
	IncludeInternal bool
}

type VisitorSummaryRow struct {
	Visitors          int64
	ReturningVisitors int64
	DailyVisitors     int64
}

func (q *Queries) VisitorSummary(ctx context.Context, arg VisitorSummaryParams) (VisitorSummaryRow, error) {
	row := q.db.QueryRow(ctx, visitorSummary,
		arg.FromTs,
		arg.ToTs,
		arg.Locale,
		arg.Release,
		arg.IncludeInternal,
	)
	var i VisitorSummaryRow
	err := row.Scan(&i.Visitors, &i.ReturningVisitors, &i.DailyVisitors)
	return i, err
}
