name: 'Repository Hygiene'

'on':
  pull_request:

permissions:
  contents: 'read'
  pull-requests: 'read'

jobs:
  repository-hygiene:
    uses: 'JorisJonkers-dev/github-workflows/.github/workflows/repository-hygiene-guard.yml@1efce81af819868fb2f5fd99ee7b04a1275845d8' # v0.18.0
    secrets: 'inherit'
